name: Update Existing OTX Pulse

on:
  schedule:
    - cron: '0 2 * * *'  # Schedule to run at 2 AM UTC every day

jobs:
  update-pulse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install OTXv2

      - name: Update Existing Pulse with Malicious IPs
        env:
          OTX_API_KEY: ${{ secrets.OTX_API_KEY }}
        run: python update_otx_pulse.py
