name: Update CDN IP Whitelists

on:
  schedule:
    - cron: '0 0 * * *'  # Daily updates at midnight UTC
  workflow_dispatch:  # Manual trigger option

permissions:
  contents: write

jobs:
  update-cdn-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create combined CDN IP file
        run: |
          mkdir -p whitelist
          # Cloudflare CDN IPs
          echo "#Cloudflare CDN IPs" > whitelist/cdnips.txt
          curl -s https://www.cloudflare.com/ips-v4/ >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt
          curl -s https://www.cloudflare.com/ips-v6/ >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt

          # Fastly CDN IPs
          echo "" >> whitelist/cdnips.txt
          echo "#Fastly CDN IPs" >> whitelist/cdnips.txt
          curl -s https://api.fastly.com/public-ip-list | jq -r '.addresses[], .ipv6_addresses[]' >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt

          # Akamai CDN IPs
          echo "#Akamai CDN IPs" >> whitelist/cdnips.txt
          curl -s https://techdocs.akamai.com/property-manager/pdfs/akamai_ipv4_CIDRs.txt >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt

          # Tailscale DERP IPs
          echo "#Tailscale DERP IPv4s" >> whitelist/cdnips.txt
          curl -s https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv4' >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt
          echo "#Tailscale DERP IPv6s" >> whitelist/cdnips.txt
          curl -s https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv6' >> whitelist/cdnips.txt
          echo "" >> whitelist/cdnips.txt
          
          #Tailscale Control Panel IPs
          echo "#Tailscale Control Panel IPs" >> whitelist/cdnips.txt
          dig +short @1.1.1.1 login.tailscale.com >> whitelist/cdnips.txt
          dig +short @1.1.1.1 controlplane.tailscale.com >> whitelist/cdnips.txt
          dig +short @1.1.1.1 log.tailscale.com >> whitelist/cdnips.txt
          dig +short @1.1.1.1 log.tailscale.io >> whitelist/cdnips.txt

      # Commit changes with proper error handling
      - name: Commit updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add whitelist/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CDN IP Whitelist"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
