name: Update CDN IP Whitelists

on:
  schedule:
    - cron: '0 0 * * *'  # Daily updates at midnight UTC
  workflow_dispatch:  # Manual trigger option

permissions:
  contents: write

jobs:
  update-cdn-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Cloudflare (CDN/WAF)
      - name: Get Cloudflare IPv4
        run: curl -s https://www.cloudflare.com/ips-v4/ -o whitelist/cloudflare-v4.txt
      - name: Get Cloudflare IPv6
        run: curl -s https://www.cloudflare.com/ips-v6/ -o whitelist/cloudflare-v6.txt

      # Fastly (CDN)
      - name: Get Fastly IPs
        run: |
          curl -s https://api.fastly.com/public-ip-list | \
          jq -r '.addresses[], .ipv6_addresses[]' > whitelist/fastly.txt

      # Akamai (Edge/CDN) - Updated with correct URL
      - name: Get Akamai IPs
        run: curl -s https://techdocs.akamai.com/property-manager/pdfs/akamai_ipv4_CIDRs.txt -o whitelist/akamai.txt

      # Commit changes with proper error handling
      - name: Commit updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add whitelist/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CDN IP lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
