name: Filter Blocklist Update (Test)

on:
  push:
    paths:
      - 'iplist/master_malicious_iplist.txt'
      - 'iplist/permanent_IPList.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  filter-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set executable permission for filter script
        run: chmod +x script/run_filter_blocklist.sh

      - name: Run filter blocklist script
        run: bash script/run_filter_blocklist.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iplist/filtered_malicious_iplist.txt iplist/filteredpermanentmaliciousiplist.txt iplist/removedips/ips_removed_from_mainblocklist.txt iplist/removedips/ips_removed_from_permanentblocklist.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Filter Blocklist update on $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
