name: Honeypot Unique IPs

#on:
#  schedule:
#    - cron: '0 16 * * *' # Runs daily at midnight
#  workflow_dispatch: # Allows manual trigger from the GitHub UI
on:
  push:
    paths:
      - 'iplist/honeypot/honeypot_extracted_feed.txt'
      
permissions:
  contents: write  # Required to push changes

jobs:
  aggregate_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Date Variables
        id: date_vars
        run: |
          echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV
          echo "CURRENT_MONTH=$(date +'%m')" >> $GITHUB_ENV

      - name: Aggregate IPs
        run: |
          # Construct the output directory based on the current year and month
          OUTPUT_DIR="data/output/${{ env.CURRENT_YEAR }}/${{ env.CURRENT_MONTH }}/"
          echo "Output directory: $OUTPUT_DIR"

          # Create or truncate the output file
          FILE_PATH="iplist/honeypot/honeypot_extracted_feed.txt"
          > $FILE_PATH
          echo "Output file: $FILE_PATH" 

          # Loop through the output files in the current month for the current year
          for file in "${OUTPUT_DIR}output_"*; do
            if [[ -f "$file" ]]; then
              cat "$file" >> $FILE_PATH
            else
              echo "No files found matching pattern ${OUTPUT_DIR}output_*"
            fi
          done

          # Sort and remove duplicates
          sort -u "$FILE_PATH" -o "$FILE_PATH"

      - name: Commit and Push Changes
        run: |
          current_date=$(TZ="Australia/Sydney" date "+%Y-%m-%d %H:%M:%S")
    
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
    
          # Fetch latest changes from the remote
          git fetch origin
    
          # Merge changes if there are updates
          git merge origin/main
    
          # Stage the file and commit changes
          git add iplist/honeypot/honeypot_extracted_feed.txt
          git commit -m "Update unique IPs - ${current_date}" || echo "No changes to commit"
    
          # Push changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
