name: Daily C2 IP Feed Update

on:
#  schedule:
#    - cron: '30 14 * * *'  # Daily at 4:00 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-external-sources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [
          {
            url: "https://raw.githubusercontent.com/montysecurity/C2-Tracker/refs/heads/main/data/all.txt",
            name: "c2trackermonsecurity"
          },
          {
            url: "https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/refs/heads/master/feeds/IPC2s-90day.csv",
            name: "drbra_ipc2s90days"
          },
          {
            url: "https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/refs/heads/master/feeds/IPC2s.csv",
            name: "drbra_ipc2s"
          },
          {
            url: "https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/refs/heads/master/feeds/IPC2s-30day.csv",
            name: "drbra_ipc2s30days"
          }
          # Add new sources here as comma-separated objects
        ]
    steps:
    - name: Download and process ${{ matrix.source.name }}
      run: |
        curl -sSfL "${{ matrix.source.url }}" -o raw_${{ matrix.source.name }}.txt
        grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' raw_${{ matrix.source.name }}.txt > processed_${{ matrix.source.name }}.txt
        rm raw_${{ matrix.source.name }}.txt

    - name: Upload processed ${{ matrix.source.name }}
      uses: actions/upload-artifact@v4
      with:
        name: processed-${{ matrix.source.name }}
        path: processed_${{ matrix.source.name }}.txt

  combine-lists:
    needs: process-external-sources
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all processed sources
      uses: actions/download-artifact@v4.1.7
      with:
        path: processed-sources

    - name: Set current timestamp
      run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Verify file paths
      run: |
        echo "Directory structure:"
        find processed-sources -type f
        echo "Files found: $(find processed-sources -name 'processed_*.txt' | wc -l)"

    - name: Combine all IP sources
      run: |
        cat processed-sources/*/processed_*.txt > iplist/C2IPs/osintc2feed.txt
  
    - name: Remove Deduplicate IPs in Permanent List
      run: |    
          # Sort and deduplicate the file in-place
          sort -u iplist/C2IPs/osintc2feed.txt -o iplist/C2IPs/osintc2feed.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add iplist/C2IPs/osintc2feed.txt
        
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update C2 IP OSINT Feed - ${{ env.DATE }}"
          git push
        fi
