name: Daily Malicious IP List Update

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 4:00 AM UTC
  push:
    paths:
      - 'iplist/honeypot/honeypot_extracted_feed.txt'
      - 'iplist/C2IPs/master_c2_iplist.txt'
      - 'iplist/honeypot/osinthoneypotfeed.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-external-sources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [
          {
            url: "https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/mass_scanner.txt",
            name: "maltrail_scanners"
          },
          {
            url: "https://www.botvrij.eu/data/ioclist.ip-dst.raw",
            name: "botvrij_eu"
          },
          {
            url: "https://feodotracker.abuse.ch/downloads/ipblocklist.txt",
            name: "feodotracker"
          },
          {
            url: "https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt",
            name: "feodotracker_recommended"
          },
          {
            url: "https://lists.blocklist.de/lists/all.txt",
            name: "Blocklist_de_all"
          },
          {
            url: "https://threatview.io/Downloads/IP-High-Confidence-Feed.txt",
            name: "ThreatView_High_Confidence"
          },
          {
            url: "https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/7.txt",
            name: "IPsumLevel_7"
          },
          {
            url: "https://cinsscore.com/list/ci-badguys.txt",
            name: "CINS_Score"
          },
          {
            url: "https://osint.digitalside.it/Threat-Intel/lists/latestips.txt",
            name: "digitalside"
          },
          {
            url: "https://raw.githubusercontent.com/duggytuxy/malicious_ip_addresses/refs/heads/main/botnets_zombies_scanner_spam_ips.txt",
            name: "duggytuxy"
          },
          {
            url: "https://security.etnetera.cz/feeds/etn_aggressive.txt",
            name: "etnetera.cz"
          },
          {
            url: "https://rules.emergingthreats.net/blockrules/compromised-ips.txt",
            name: "emergingthreats-compromised"
          },
          {
            url: "https://blocklist.greensnow.co/greensnow.txt",
            name: "greensnow.co"
          },
          {
            url: "https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/8.txt",
            name: "ipsum_level8"
          },
          {
            url: "https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/5.txt",
            name: "ipsum_level5"
          },
          {
            url: "https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/6.txt",
            name: "ipsum_level6"
          }
          
          # Add new sources here as comma-separated objects
        ]
      fail-fast: false  # Continue even if some matrix jobs fail
    steps:
    - name: Download and process ${{ matrix.source.name }}
      continue-on-error: true  # Don't fail the matrix job for this step
      run: |
        curl -sSfL "${{ matrix.source.url }}" -o raw_${{ matrix.source.name }}.txt
        grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' raw_${{ matrix.source.name }}.txt > processed_${{ matrix.source.name }}.txt
        rm raw_${{ matrix.source.name }}.txt

    - name: Upload processed ${{ matrix.source.name }}
      uses: actions/upload-artifact@v4
      with:
        name: processed-${{ matrix.source.name }}
        path: processed_${{ matrix.source.name }}.txt

  combine-lists:
    needs: process-external-sources
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all processed sources
      uses: actions/download-artifact@v4.1.7
      with:
        path: processed-sources

    - name: Set current timestamp
      run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Combine all IP sources
      run: |
        cat processed-sources/processed-*/*.txt \
            iplist/honeypot/honeypot_extracted_feed.txt \
            iplist/C2IPs/osintc2feed.txt \
            iplist/honeypot/osinthoneypotfeed.txt \
            iplist/C2IPs/master_c2_iplist.txt | sort -u > master_malicious_iplist.txt
    
    - name: Append to Permanent IP List
      run: |
        cat master_malicious_iplist.txt >> permanent_IPList.txt
    
    - name: Remove Deduplicate IPs in Permanent List
      run: |    
          # Sort and deduplicate the file in-place
          sort -u permanent_IPList.txt -o permanent_IPList.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add master_malicious_iplist.txt permanent_IPList.txt
        
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update Malicious IP Feed - ${{ env.DATE }}"
          git push
        fi
