name: Daily Malicious IP List Update

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4:00 AM UTC
  push:
    paths:
      - 'honeypot/honeypot_iplist.txt'
      - 'C2IPFeed/master_c2_iplist.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-external-sources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [
          {
            url: "https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/mass_scanner.txt",
            name: "maltrail_scanners"
          },
          {
            url: "https://www.botvrij.eu/data/ioclist.ip-dst.raw",
            name: "botvrij_eu"
          },
          {
            url: "https://feodotracker.abuse.ch/downloads/ipblocklist.txt",
            name: "feodotracker"
          },
          {
            url: "https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt",
            name: "feodotracker_recommended"
          },
          {
            url: "https://lists.blocklist.de/lists/all.txt",
            name: "Blocklist_de_all"
          }
          # Add new sources here as comma-separated objects
        ]
    steps:
    - name: Download and process ${{ matrix.source.name }}
      run: |
        curl -sSfL "${{ matrix.source.url }}" -o raw_${{ matrix.source.name }}.txt
        grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' raw_${{ matrix.source.name }}.txt > processed_${{ matrix.source.name }}.txt
        rm raw_${{ matrix.source.name }}.txt

    - name: Upload processed ${{ matrix.source.name }}
      uses: actions/upload-artifact@v3
      with:
        name: processed-${{ matrix.source.name }}
        path: processed_${{ matrix.source.name }}.txt

  combine-lists:
    needs: process-external-sources
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all processed sources
      uses: actions/download-artifact@v3
      with:
        path: processed-sources

    - name: Set current timestamp
      run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Combine all IP sources
      run: |
        cat processed-sources/processed-*/*.txt \
            honeypot/honeypot_iplist.txt \
            C2IPFeed/master_c2_iplist.txt | sort -u > master_malicious_iplist.txt

      - name: Commit and Push Changes
        run: |
        
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"  
          # Fetch latest changes from the remote
          git fetch origin
          # Merge changes if there are updates
          git merge origin/main
          # Stage the file and commit changes
          git add honeypot/honeypot_iplist.txt
          git commit -m "Auto-update Malicious IP Feed - ${{ env.DATE }}" || echo "No changes to commit"
          # Push changes
          git push origin main
