name: Daily Malicious IP List Update

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4:00 AM UTC
  push:
    paths:
      - 'honeypot/honeypot_iplist.txt'
      - 'C2IPFeed/master_c2_iplist.txt'
  workflow_dispatch:

env:
  SOURCES: |
    [
      {
        "url": "https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/mass_scanner.txt",
        "name": "maltrail_scanners"
      }
    ]

permissions:
  contents: write

jobs:
  process-external-sources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{ fromJson(env.SOURCES) }}
    steps:
    - name: Download and process ${{ matrix.source.name }}
      run: |
        # Download and clean external source
        curl -sSfL "${{ matrix.source.url }}" -o raw_${{ matrix.source.name }}.txt
        grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' raw_${{ matrix.source.name }}.txt > processed_${{ matrix.source.name }}.txt
        rm raw_${{ matrix.source.name }}.txt

    - name: Upload processed ${{ matrix.source.name }}
      uses: actions/upload-artifact@v3
      with:
        name: processed-${{ matrix.source.name }}
        path: processed_${{ matrix.source.name }}.txt

  combine-lists:
    needs: process-external-sources
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all processed sources
      uses: actions/download-artifact@v3
      with:
        path: processed-sources

    - name: Set current timestamp
      run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Combine all IP sources
      run: |
        # Combine external sources
        cat processed-sources/processed-*/*.txt > combined_external.txt
        
        # Add local lists
        cat combined_external.txt \
            honeypot/honeypot_iplist.txt \
            C2IPFeed/master_c2_iplist.txt | sort -u > master_malicious_ip.txt
        
        # Cleanup
        rm combined_external.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add master_malicious_iplist.txt
        
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update Malicious IP Feed - ${{ env.DATE }}"
          git push
        fi
