name: Daily Malicious IP List Update

on:
  push:
    paths:
      - 'honeypot/honeypot_iplist.txt'
      - 'C2IPFeed/master_c2_iplist.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4:00 AM UTC

permissions:
  contents: write

jobs:
  update-master-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set current timestamp
      run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Combine IP lists and remove duplicates
      run: |
        cat honeypot/honeypot_iplist.txt C2IPFeed/master_c2_iplist.txt | sort -u > master_malicious_ip.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add master_malicious_ip.txt
        
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update master_malicious_ip.txt - ${{ env.DATE }}"
          git push
        fi
